name = "SelfConcordantSmoothOptimization"
uuid = "d352d416-c122-4e2b-b229-b93695c65420"
authors = ["Adeyemi Damilare Adeoye <58517568+adeyemiadeoye@users.noreply.github.com> and Alberto Bemporad"]
version = "0.1.7"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]
julia = "1.9 - 1.11"
ForwardDiff = "1.3.0"
LinearSolve = "3.52.0"
IntervalSets = "0.7.13"
MLUtils = "0.4.8"
StatsBase = "0.34.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
